receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
  tail_sampling:
    decision_wait: 10s
    num_traces: 10000
    policies:
      - name: keep-errors
        type: status_code
        status_code:
          status_codes: [ ERROR ]

      - name: keep-slow
        type: latency
        latency:
          threshold_ms: 500

      - name: probabilistic-sample
        type: probabilistic
        probabilistic:
          sampling_percentage: 10

exporters:
  debug:
    verbosity: detailed
  otlp/tempo:
    endpoint: "grafana-tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch, tail_sampling]
      exporters: [debug, otlp/tempo]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]